name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Install dependencies
        run: npm ci
      - name: Ensure ESLint is installed
        run: npm install --save-dev eslint
      - name: Ensure ESLint config file exists
        run: |
          if [ ! -f .eslintrc.js ] && [ ! -f .eslintrc.json ] && [ ! -f .eslintrc.yml ]; then
            echo "No ESLint config file found. Creating a default one..."
            echo '{
              "env": { "browser": true, "es2021": true },
              "extends": ["eslint:recommended"],
              "parserOptions": { "ecmaVersion": "latest", "sourceType": "module" },
              "rules": {}
            }' > .eslintrc.json
          fi
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
